// 技能配置
export const skillConfig = [
  {
    name: "必杀",
    description: "物理攻击时有几率造成双倍伤害",
    type: "物理",
    icon: "fa-fist-raised",
    mode: "被动",
  },
  {
    name: "连击",
    description: "物理攻击时可能连续攻击两次",
    type: "物理",
    icon: "fa-strikethrough",
    mode: "被动",
  },
  {
    name: "法术暴击",
    description: "法术攻击时有几率造成双倍伤害",
    type: "法术",
    icon: "fa-bolt",
    mode: "被动",
  },
  {
    name: "反震",
    description: "受到物理攻击时有几率反弹伤害",
    type: "防御",
    icon: "fa-shield-alt",
    mode: "被动",
  },
  {
    name: "感知",
    description: "可以感知到隐身的单位",
    type: "辅助",
    icon: "fa-eye",
    mode: "被动",
  },
  {
    name: "偷袭",
    description: "物理攻击时不会受到反击",
    type: "物理",
    icon: "fa-dagger",
    mode: "被动",
  },
  {
    name: "神佑复生",
    description: "战斗中死亡时有几率复活",
    type: "生存",
    icon: "fa-life-ring",
    mode: "被动",
  },
  {
    name: "隐身",
    description: "可以隐藏自己的身形",
    type: "辅助",
    icon: "fa-moon",
    mode: "主动",
  },
  {
    name: "魔之心",
    description: "增加法术伤害",
    type: "法术",
    icon: "fa-fire",
    mode: "被动",
  },
  {
    name: "敏捷",
    description: "提升自身速度",
    type: "速度",
    icon: "fa-running",
    mode: "被动",
  },
  {
    name: "幸运",
    description: "增加躲避暴击的几率",
    type: "防御",
    icon: "fa-four-leaf-clover",
    mode: "被动",
  },
  {
    name: "强力",
    description: "增加物理攻击伤害",
    type: "物理",
    icon: "fa-bullseye",
    mode: "被动",
  },
  {
    name: "法术连击",
    description: "法术攻击时可能连续攻击两次",
    type: "法术",
    icon: "fa-bolt-lightning",
    mode: "被动",
  },
  {
    name: "夜战",
    description: "夜间战斗能力增强",
    type: "物理",
    icon: "fa-moon-stars",
    mode: "被动",
  },
  {
    name: "法术波动",
    description: "法术伤害在一定范围内波动",
    type: "法术",
    icon: "fa-wave-square",
    mode: "被动",
  },
  {
    name: "水漫金山",
    description: "施展水属性法术攻击多个目标",
    type: "法术",
    icon: "fa-water",
    mode: "主动",
  },
  {
    name: "烈火",
    description: "施展火属性法术攻击目标",
    type: "法术",
    icon: "fa-fire-flame-curved",
    mode: "主动",
  },
  {
    name: "法术防御",
    description: "增加法术防御能力",
    type: "防御",
    icon: "fa-shield-magic",
    mode: "被动",
  },
  {
    name: "泰山压顶",
    description: "施展土属性法术攻击目标",
    type: "法术",
    icon: "fa-mountain",
    mode: "主动",
  },
  {
    name: "奔雷咒",
    description: "施展雷属性法术攻击目标",
    type: "法术",
    icon: "fa-bolt-circle",
    mode: "主动",
  },
  {
    name: "反击",
    description: "受到物理攻击时有几率反击对方",
    type: "物理",
    icon: "fa-arrow-rotate-left",
    mode: "被动",
  },
  {
    name: "落岩",
    description: "施展土属性法术攻击目标",
    type: "法术",
    icon: "fa-rock",
    mode: "主动",
  },
  {
    name: "水攻",
    description: "施展水属性法术攻击目标",
    type: "法术",
    icon: "fa-droplet",
    mode: "主动",
  },
  {
    name: "感知强化",
    description: "增强感知隐身单位的能力",
    type: "辅助",
    icon: "fa-eye-dropper",
    mode: "被动",
  },
  {
    name: "隐身强化",
    description: "延长隐身持续时间",
    type: "辅助",
    icon: "fa-moon-stars",
    mode: "被动",
  },
  {
    name: "神佑强化",
    description: "提高神佑复生的触发几率",
    type: "生存",
    icon: "fa-life-ring",
    mode: "被动",
  },
  {
    name: "魔之心强化",
    description: "进一步增加法术伤害",
    type: "法术",
    icon: "fa-fire",
    mode: "被动",
  },
  {
    name: "敏捷强化",
    description: "大幅提升自身速度",
    type: "速度",
    icon: "fa-running",
    mode: "被动",
  },
  {
    name: "幸运强化",
    description: "极大增加躲避暴击的几率",
    type: "防御",
    icon: "fa-four-leaf-clover",
    mode: "被动",
  },
  {
    name: "强力强化",
    description: "显著增加物理攻击伤害",
    type: "物理",
    icon: "fa-bullseye",
    mode: "被动",
  },
  {
    name: "必杀强化",
    description: "提高必杀触发几率和伤害倍数",
    type: "物理",
    icon: "fa-fist-raised",
    mode: "被动",
  },
  {
    name: "连击强化",
    description: "增加连击次数和触发几率",
    type: "物理",
    icon: "fa-strikethrough",
    mode: "被动",
  },
];